### ISSUE TITLE
Need to make it clear on README tutorial about what codes need to change.

### ISSUE THREAD

**Issue by cheyaohu** [srinidaruna/bookmark-utils#16]
Code in tutorial in README (codes that need to copy and paste into a glue job) does not work.

So I cloned the git code and tried it with what you had in your examples directory instead and that worked.

I updated it to use my own s3 bucket and prefix and that seemed to work for the codes in tutorial. 

Need to make it clear on README tutorial about what codes need to change.

Maxine Wee

**Comment by srinidaruna** [comment]
Update the documentation to be easily understandable to first time Glue users:

Refine the documentation to explain why this utility is needed. Start with explaining what problem it solves, which is avoiding re-processing of the files. Once the high level explanation is clear, add a link to Glue PySpark bookmarks documentation so the end users will be able to understand what is bookmarks.

**Comment by cheyaohu** [comment]
README has been revised accordingly. The revised version will be in the next pull request.
